export const PLANKSIZE_DELETE_RESET = 'PLANKSIZE_DELETE_RESET'
export const PLANKSIZE_DELETE_SET_ERROR = 'PLANKSIZE_DELETE_SET_ERROR'
export const PLANKSIZE_DELETE_SET_DELETED = 'PLANKSIZE_DELETE_SET_DELETED'
export const PLANKSIZE_DELETE_TOGGLE_LOADING = 'PLANKSIZE_DELETE_TOGGLE_LOADING'
