export const PLANK_SHOW_RESET = 'PLANK_SHOW_RESET'
export const PLANK_SHOW_SET_ERROR = 'PLANK_SHOW_SET_ERROR'
export const PLANK_SHOW_SET_RETRIEVED = 'PLANK_SHOW_SET_RETRIEVED'
export const PLANK_SHOW_TOGGLE_LOADING = 'PLANK_SHOW_TOGGLE_LOADING'
