export const WOODTYPE_DELETE_RESET = 'WOODTYPE_DELETE_RESET'
export const WOODTYPE_DELETE_SET_ERROR = 'WOODTYPE_DELETE_SET_ERROR'
export const WOODTYPE_DELETE_SET_DELETED = 'WOODTYPE_DELETE_SET_DELETED'
export const WOODTYPE_DELETE_TOGGLE_LOADING = 'WOODTYPE_DELETE_TOGGLE_LOADING'
