export const WOODTYPE_SHOW_RESET = 'WOODTYPE_SHOW_RESET'
export const WOODTYPE_SHOW_SET_ERROR = 'WOODTYPE_SHOW_SET_ERROR'
export const WOODTYPE_SHOW_SET_RETRIEVED = 'WOODTYPE_SHOW_SET_RETRIEVED'
export const WOODTYPE_SHOW_TOGGLE_LOADING = 'WOODTYPE_SHOW_TOGGLE_LOADING'
