export const ELEMENT_DELETE_RESET = 'ELEMENT_DELETE_RESET'
export const ELEMENT_DELETE_SET_ERROR = 'ELEMENT_DELETE_SET_ERROR'
export const ELEMENT_DELETE_SET_DELETED = 'ELEMENT_DELETE_SET_DELETED'
export const ELEMENT_DELETE_TOGGLE_LOADING = 'ELEMENT_DELETE_TOGGLE_LOADING'
