export const PLANKSIZE_SHOW_RESET = 'PLANKSIZE_SHOW_RESET'
export const PLANKSIZE_SHOW_SET_ERROR = 'PLANKSIZE_SHOW_SET_ERROR'
export const PLANKSIZE_SHOW_SET_RETRIEVED = 'PLANKSIZE_SHOW_SET_RETRIEVED'
export const PLANKSIZE_SHOW_TOGGLE_LOADING = 'PLANKSIZE_SHOW_TOGGLE_LOADING'
