export const PLANK_DELETE_RESET = 'PLANK_DELETE_RESET'
export const PLANK_DELETE_SET_ERROR = 'PLANK_DELETE_SET_ERROR'
export const PLANK_DELETE_SET_DELETED = 'PLANK_DELETE_SET_DELETED'
export const PLANK_DELETE_TOGGLE_LOADING = 'PLANK_DELETE_TOGGLE_LOADING'
