export const ELEMENT_SHOW_RESET = 'ELEMENT_SHOW_RESET'
export const ELEMENT_SHOW_SET_ERROR = 'ELEMENT_SHOW_SET_ERROR'
export const ELEMENT_SHOW_SET_RETRIEVED = 'ELEMENT_SHOW_SET_RETRIEVED'
export const ELEMENT_SHOW_TOGGLE_LOADING = 'ELEMENT_SHOW_TOGGLE_LOADING'
